### ISSUE TITLE
PowerBI RS Download link: please update to the latest Download link

### ISSUE THREAD

**Issue by arcus4** [MicrosoftDocs/powerbi-docs.de-de#10]
https://www.microsoft.com/download/details.aspx?id=56722 is an older version of PowerBI RS.
Pls update to the latest Download link https://www.microsoft.com/en-us/download/details.aspx?id=57270

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 69db1b96-91ed-2440-5a1c-873a19d7ee47
* Version Independent ID: db0e2007-963b-44a5-9b6e-5be35481473e
* Content: [Installieren von Power BI-Berichtsserver - Power BI](https://docs.microsoft.com/de-de/power-bi/report-server/install-report-server#feedback)
* Content Source: [powerbi-docs/report-server/install-report-server.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/report-server/install-report-server.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @arcus4
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Hello, @arcus4 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/1602.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
