### ISSUE TITLE
how to "order by column" if the data source is SSAS tabular?

### ISSUE THREAD

**Issue by aisbergde** [MicrosoftDocs/powerbi-docs.de-de#13]
"Sort by Column" is not available if the database is SSAS tabular.
How to sort by column in this case?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sortieren nach Spalten in Power BI Desktop - Power BI](https://docs.microsoft.com/de-de/power-bi/desktop-sort-by-column)
* Content Source: [powerbi-docs/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #2046](https://github.com/MicrosoftDocs/powerbi-docs/issues/2046) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @aisbergde, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/2046. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
