### ISSUE TITLE
non-profit pricing plan is not available

### ISSUE THREAD

**Issue by chrsh18** [MicrosoftDocs/powerbi-docs.de-de#2]
The non-profit pricing plan is not available, link is broken. Please fix this. TIA

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d877b0ce-2e0b-dca4-709d-24b4e5a374b4
* Version Independent ID: 8d727d5a-7e46-62a7-8530-882ee9653640
* Content: [Häufig gestellte Fragen zu Power BI - Power BI](https://docs.microsoft.com/de-de/power-bi/service-frequently-asked-questions)
* Content Source: [powerbi-docs/service-frequently-asked-questions.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/service-frequently-asked-questions.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #136](https://github.com/MicrosoftDocs/powerbi-docs/issues/136) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @chrsh18 , 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/136. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
