### ISSUE TITLE
Paginated Reports in Power BI Service

### ISSUE THREAD

**Issue by mpoeckl** [MicrosoftDocs/powerbi-docs.de-de#3]
According to the list, paginated reports are not available in Power BI Service. While the feature is still in preview for the Power BI Service, it is possible to publish SSRS reports to Power BI Service... Therefore "No" should change to "In preview".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Vergleich zwischen Power BI-Berichtsserver und Power BI-Dienst - Power BI](https://docs.microsoft.com/de-de/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #397](https://github.com/MicrosoftDocs/powerbi-docs/issues/397) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @mpoeckl 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/397.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
