### ISSUE TITLE
JSON not valid

### ISSUE THREAD

**Issue by ImkeF** [MicrosoftDocs/powerbi-docs.de-de#4]
The JSON for "Properties within each card" is not valid.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Verwenden von Berichtdesigns in Power BI Desktop - Power BI](https://docs.microsoft.com/de-de/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #822](https://github.com/MicrosoftDocs/powerbi-docs/issues/822) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @ImkeF 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/822

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
